export const Data = [
  {
    Username: "Joe",
    Address: "53A Pringle Street",
    PostCode: "SE6 4JL",
    Details: "After we had signed the contracts paid the deposit and moved in the landlord tried to ask for an extra £300 from each of the tenants. He threatened us with court if we didn’t pay and those that did never saw it again.",
    Date: "Nov-2022",
    Score:67,
  },
  {
    Username: "Lewis",
    Address: "32 Walker Road",
    PostCode: "BS7 9PR",
    Details: "The window frames are rotting in the flat which causes serious damp and draft issues in the winter the landlord claims to not have the money to fix them but owns over ten properties in the area. There is also a serious penetrating damp problem in two of the bedrooms that they have yet to look at despite being repeatedly reminded of it since October. They also left us without a working shower for six months.",
    Date: "Feb-2022",
    Score:20,
   },
  {
    "Username": "Lilli",
    "Address": "186 Frazzle Road",
    "PostCode": " E14 3HJ",
    "Details": "Landlord tried to ban us from having visitors to the house.",
    "Date": "Jan-2021",
    "Score":30,
   },
  {
    "Username": "Jonah",
    "Address": "75 Frazzle Road",
    "PostCode": "BN2 5JR",
    "Details": "When we moved in there was an angry wasps nest in one of the wall cavity this was in winter but it was still warm enough for them inside. The landlord refused to do anything about it for 4 months and demanded that we continue to pay full rent or go to court. When they did come to fix it, they put sticky tape over the cracks, the problem did not go away.",
    "Date": "Mar-2022",
    "Score":30,
   },
  {
    "Username": "Megan",
    "Address": "33 Quaver Road",
    "PostCode": "NG3 5TD",
    "Details": "We left this flat three years ago. Today we got an email from the landlord asking for £200 for damages.",
    "Date": "Jan-2022",
    "Score":50,
   },
  {
    "Username": "Bex",
    "Address": "31 Dacre Road",
    "PostCode": "SE5 5RF",
    "Details": "The mould is so bad here that one of our housemates had to go on special medication to help with his breathing. We also had to abandon various pieces of clothing and furniture as they were ruined by the mould.",
    "Date": "JUL-2021",
    "Score":70,
   },
  {
    "Username": "Yalin",
    "Address": "22 Brindish Road",
    "PostCode": "L8 5HQ",
    "Details": "The central heating does not work. The landlord claims that central heating is not included in the contract and that the house is let ‘as is’. It has radiators and a boiler.",
    "Date": "Nov-2021",
    "Score":28,
   },
  {
    "Username": "Cathy",
    "Address": "100 Downham Avenu",
    "PostCode": "E14 9RT",
    "Details": "I left a plastic bin in the room for the next tenants. The landlord took £100 out of my deposit for removals.",
    "Date": "Dec-2021",
    "Score":63,
   },
  {
    "Username": "Ali",
    "Address": "23 Stillness Road",
    "PostCode": "BS5 3ES",
    "Details": "The landlord tried to take money from the deposit because there was rubbish in the wheely bin.",
    "Date": "Aug-2021",
    "Score":90,
   },
  {
    "Username": "Simone",
    "Address": "45 Kincaid Road",
    "PostCode": "BR6 7UI",
    "Details": "The landlord turned out to be unlicensed but rented his house out to ten of us. The conservatory collapsed about a month in and water runs down the light fitting when someone is in the shower. We have never met the landlord face to face.",
    "Date": "May-2022",
    "Score":68,
   },
  {
    "Username": "Ollie",
    "Address": "33 Elm Grove",
    "PostCode": "BN2 5DS",
    "Details": "The door of the bedroom that comes off the living room often breaks and gets stuck open. Meaning whoever is in there has no privacy.",
    "Date": "Jan-2021",
    "Score":23,
   },
  {
    "Username": "Callum",
    "Address": "87A DOver Road",
    "PostCode": "NE3 7KN",
    "Details": "There is a type of fungus that looks like tiramisu that grows in the corners of all the downstairs rooms. It put one of our housemates in hospital due to allergies.",
    "Date": "Feb-2022",
    "Score":53,
   },
  {
    "Username": "Zane",
    "Address": "99 Gyros Lane",
    "PostCode":  "CF10 1AX",
    "Details": "We were 3 months into the tenancy when the landlord came round and demanded a £10 cash fine on the spot for some litter in the front garden.",
    "Date": "Feb-2022",
    "Score":40,
   },
  {
    "Username": "Rosella",
    "Address": "56 Horfield Avenue",
    "PostCode": "SW9 5RX",
    "Details": "The house has serious mould and the landlords only suggestions is to keep all the windows open in winter.",
    "Date": "May-2021",
    "Score":34,
   },
  {
    "Username": "Sid",
    "Address": "31 Fairview Street",
    "PostCode": "CR4 9HS",
    "Details": "The landlord didn’t put our deposit in a protection scheme then tried to deny it by saying we were checking it wrong.",
    "Date": "May-2022",
    "Score":57,
   },
  {
    "Username": "Coco",
    "Address": "56 Palace Road",
    "PostCode": "CTR 8AB",
    "Details": "The house is old and one of the key beams that supports the first floor had entirely rotted through and collapsed into the bedroom below. The landlord blamed us for “showering too hard” despite the fact that this level of rot would have taken years and we had been there for 5 months.",
    "Date": "Aug-2021",
    "Score":36,
   },
  {
    "Username": "Rizwan",
    "Address": "59 Newcastle Road",
    "PostCode": "SW2 5SA",
    "Details": "The boiler breaks repeatedly and the landlord tried to fix it by throwing lit matches at it.",
    "Date": "Oct-2021",
    "Score":15,
   },
  {
    "Username": "Mustafa",
    "Address": "150 Everton Close",
    "PostCode": "PL3 6YU",
    "Details": "There is a rats nest in the neighbours overgrown garden and they regularly find their way into the house.",
    "Date": "Oct-2021",
    "Score":56,
   },
  {
    "Username": "Rozine",
    "Address": "31 Belmont Hill",
    "PostCode": "LS6 1PY",
    "Details": "The electricity in the kitchen regularly blows out meaning you can only cook things in the oven. The landlords have bodged fixing it 5 times and say its too expensive to do properly.",
    "Date": "Apr-2022",
    "Score":89,
   },
  {
    "Username": "Hugo",
    "Address": "Sep-2021",
    "PostCode": "BR3 3MO",
    "Details": "There is a leak from the shower to the bathroom that the landlord has only ever painted over.",
    "Date": "Dec-2021",
    "Score":67,
   },
  {
    "Username": "Grant",
    "Address": "Flat 3 Southend House",
    "PostCode": "M16 5FX",
    "Details": "We were deducted hundreds of pounds from our deposit because of things like fingerprints on light switches and dust on a lampshade (that was above head height)",
    "Date": "Jan-2022",
    "Score":60,
   },
  {
    "Username": "Amber",
    "Address": "15 Rovers Avenue",
    "PostCode": "BS7 9AU",
    "Details": "I was fined £150 for a broken door on a wardrobe that costs £60 new.",
    "Date": "Aug-2021",
    "Score":40,
   },
  {
    "Username": "Tilly",
    "Address": "1 Charlton Road",
    "PostCode": "N7 6FS",
    "Details": "The landlord insisted that a weekly cleaner be included in the contract. This cleaner is a friend of the landlord and will inform them of everything they see in the house. The landlord would text us continually about things like washing up or leaves in the garden like they lived there.",
    "Date": "Dec-2021",
    "Score":40,
   }

];
export default Data;
